name: T6 - Desplegar
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: LocalStack/setup-localstack@v0.2.3
        with:
          image-tag: '3'
      - run: terraform init
      - run: terraform apply -auto-approve